#swarmpit_url: http://swarmpit.local/api
#swarmpit_token: your_token_here

defaults:
  min_replica: 1
  max_replica: 10
  cpu_min: 20.0
  cpu_max: 80.0
  ram_min: 30.0
  ram_max: 85.0
  scale_cooldown_up_sec: 300
  scale_cooldown_down_sec: 600
  check_interval: 300

smtp:
  host: smtp.mailserver.com
  port: 587
  user: "user@mail.com"
  password: "secret"
  from: "autoscaler@mail.com"
  to:
    - "ops@company.com"
    - "devteam@company.com"
  starttls: true

features:
  enable_email_alerts: false
  # ha_mode: [standalone|cluster_with_leader]
  ha_mode: standalone

logging:
  level: INFO

debug:
  print_service_api: true
