enabled: true
smtp:
  host: "smtp.example.com"
  port: 587
  starttls: true
  username: "autoscaler@example.com"
  password: "REDACTED"   # consigliato usare secrets separati per credenziali in ambienti prod
from: "Swarm Autoscaler <autoscaler@example.com>"
to_default:
  - "devops@example.com"
  - "noc@example.com"
subject_prefix: "[Swarm Autoscaler]"
batch_window_seconds: 300      # finestra di raccolta eventi (5 minuti)
max_batch_events: 100          # invia prima se si raggiunge questo numero di eventi
